# Setup
title: Ben's Technical Blog
description: I'm Ben Anderson and this is my technical blog.
url: https://www.benanderson.co.uk
#paginate: 1
#paginate_path: "/page:num/"
baseurl: ""
permalink: pretty

excerpt_separator: <!--excerpt-->

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
google_analytics: G-Z4LRYCGZSX

# Specify the author for blog posts
author:
  name: Ben Anderson
  url: https://github.com/Ben-D-Anderson
  email: contact@benanderson.co.uk

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Articles
    url: /
  - title: About
    url: /about
